['Presente indicativo']
title = ['1: Настоящее время', '2: Условие "если"']
description = [
    ['Использование 1:', [
        { p = 'Факты и утверждения.' }, 
        { p = 'Не для краткосрочных процессов.' }
    ]],
    ['Пример:', [
        { p = 'El niño no come pescado.' },
        { p = 'Ребёнок не ест рыбу (никогда).' }
    ]],
    ['Использование 2:', [
        { p = 'Вероятное и возможное условие, в настоящем времени и в будущем ("если").' }
    ]],
    ['В сочетании с:'], [
        { p = 'Предложениями в настоящем времени или в будущем.' }
    ]],
    ['Пример', [
        { p = 'Si llueve mañana, me quedaré en casa.' },
        { p = 'Если завтра будет дождь, я останусь дома.' }
    ]]
]

['Presente con Estar']
title = ['Краткосрочный и постоянный процесс в настоящем времени']
description = [
    ['Использование:', [
        { p = 'Факты и утверждения.' },
        { p = 'Для краткосрочных и постоянных процессов в настоящем времени.' }
    ]],
    ['Пример:', [
        { p = 'Están durmiendo.' },
        { p = 'Они спят.' }
    ]]
]

['Preterito perfecto compuestas comunes']
title = ['Расширенное прошедшее время']
description = [
    ['Использование:', [
        { p = 'Факты и утверждения.' },
        { p =  'Продолжающееся действие/Может повторяться/Пока нет, но ещё возможно.' }
    ]],
    ['Примеры:', [
        { p = 'Ha llovido todo el día.' },
        { p = 'Весь день идёт дождь.' },
        { p = 'Me ha llamado cinco veces hoy.' },
        { p = 'Сегодня он/она звонила мне уже пять раз.' },
        { p = 'No hemos tenido problemas con este ascensor.' },
        { p = 'У нас не было проблем с этим лифтом.' }
    ]]
]

['Preterito perfecto compuestas comunes con Estar']
title = ['Процесс за последнее время']
description = [
    ['Использование:', [
        { p = 'Факты и утверждения.' },
        { p = 'Продолжающийся процесс за последнее время.' }
    ]],
    ['Пример:', [
        { p = 'He estado viajando por tres semanas.' },
        { p = 'Я путешествую уже три недели.' }
    ]]
]

['Preterito indicativo']
title = ['Прошедшее время совершенного вида']
description = [
    ['Использование:', [
        { p = 'Факты и утверждения.' },
        { p = 'Описание целого, завершенного действия в прошлом.' }
    ]],
    ['Пример:', [
        { p = 'Compré frutas ayer.' },
        { p = 'Вчера я купил фрукты.' }
    ]]
]

['Imperfecto indicativo']
title = ['Прошедшее время несовершенного вида']
description = [
    ['Использование:', [
        { p = 'Факты и утверждения.' },
        { p = 'Описание части действия или обычай в прошлом.' }
    ]],
    ['Схема:', [
        { p = 'Корень + "aba"/"ía".' }
    ]],
    ['Пример:', [
        { p = 'Yo <u>jugaba</u> en este parque cuando era niño.' },
        { p = 'Я играл в этом парке когда был ребёнком.' }
    ]]
]

['Pasado continuo']
title = ['Процесс в прошлом']
description = [
    ['Использование:', [
        { p = 'Факты и утверждения.' },
        { p = 'Описание краткосрочного процесса, во время момента в прошлом.' }
    ]],
    ['В сочетании с:', [
        { p = 'Предложениями в прошедшем времени совершенного вида.' }
    ]],
    ['Пример:', [
        { p = '<u>Estábamos comiendo</u> cuando sonó la alarma.' },
        { p = 'Мы ели, когда сработала сигнализация.' }
    ]]
]

['Pluscuamperfecto compuestas comunes']
title = ['Действие завершилось до другого момента в прошлом']
description = [
    ['Использование:', [
        { p = 'Факты и утверждения.' },
        { p = 'Действие завершилось до другого момента в прошлом.' }
    ]],
    ['В сочетании с:', [
        { p = 'Предложениями в прошедшем времени совершенного вида.' }
    ]],
    ['Пример:', [
        { p = 'Ya <u>habían inventado</u> el ascensor cuando construyeron estos edificios.' },
        { p = 'Лифт уже был изобретен когда строили эти здания.' }
    ]]
]

['Preterito anterior indicativo']
title = ['Процесс завершился как условие для другого действия']
description = [
    ['Использование:', [
        { p = 'Факты и утверждения.' },
        { p = 'Условие завершилось и затем последовало другое действие ("после того, как").' }
    ]],
    ['В сочетании с:', [
        { p = 'Предложениями в прошедшем времени совершенного вида.' }
    ]],
    ['Пример:', [
        { p = 'Cuando <u>hube terminado</u> el trabajo, me pagaron.' },
        { p = 'После того, как я закончил работу, они мне заплатили.' }
    ]]
]

['Pluscuamperfecto continuo']
title = ['Краткосрочный процесс до другого момента в прошлом']
description = [
    ['Использование:', [
        { p = 'Факты и утверждения.' },
        { p = 'Краткосрочный и постоянный процесс до другого момента в прошлом.' }
    ]],
    ['В сочетании с:', [
        { p = 'Предложениями в прошедшем времени совершенного вида.' }
    ]],
    ['Пример:', [
        { p = 'Yo <u>había estado leyendo</u> sobre canguros cuando me ofrecieron viajar a Australia.' },
        { p = 'Я <u>был занят чтением</u> о кенгуру, когда мне предложили поехать в Австралию.' }
    ]]
]

['Intencion interrumpida']
title = ['1: Прерванное намерение', '2: Предсказание в прошлом']
description = [
    ['Использование 1:', [
        { p = 'Факты и утверждения.' },
        { p = 'Прерванное намерение ("собирался").' }
    ]],
    ['В сочетании с:', [
        { p = 'Предложениями в прошедшем времени.' }
    ]],
    ['Пример:', [
        { p = '<u>Íbamos a comprar</u> una computadora nueva pero nos dijeron que es más barato reparar la vieja.' },
        { p = 'Мы собирались купить новый компьютер, но нам сказали, что дешевле отремонтировать старый.' }
    ]],
    ['Использование 2:', [
        { p = 'Предсказание в прошлом.' }
    ]],
    ['В сочетании с:'], [
        { p = 'Предложениями в прошедшем времени.' }
    ]],
    ['Пример', [
        { p = 'Creíamos que <u>ibas a llegar</u> más tarde.' },
        { p = 'Мы думали, что ты <u>доберёшься</u> позже.' }
    ]]
]

['Imperativo afirmativo']
title = ['Утвердительное повелительное наклонение']
description = [
    ['Пример', [
        { p = '¡Miren qué lindo edificio!' },
        { p = 'Посмотрите, какое красивое здание!' }
    ]]
]

['Imperativo negativo']
title = ['Отрицательное повелительное наклонение']
description = [
    ['Пример', [
        { p = '¡No toques esos cables!' },
        { p = 'Не трогай эти кабели!' }
    ]]
]

['Cohortativo afirmativo']
title = ['Гортатив (утвердительный)']
description = [
    ['Использование:', [
        { p = 'Призыв к действию с намерением участвовать в реализации желаемой ситуации ("Давайте сделаем!").' }
    ]],
    ['Пример', [
        { p = 'Hablemos mañana.' },
        { p = 'Давай поговорим завтра.' }
    ]]
]

['Cohortativo negativo']
title = ['Гортатив (отрицательный)']
description = [
    ['Использование:', [
        { p = 'Призыв к бездействию с намерением говорящего самому участвовать в реализации желаемой ситуации ("Давайте не будем делать!").' }
    ]],
    ['Пример', [
        { p = 'No nos peleemos.' },
        { p = 'Давайте не будем спорить.' }
    ]]
]

['Futuro con Ir a']
title = ['1: Будущее время (с вспомогательным глаголом)', '2: Недоверие о настоящем времени или о будущем']
description = [
    ['Использование 1:', [
        { p = 'Обещания и предсказания.' }, 
        { p = 'Будущее время (с вспомогательным глаголом).' }
    ]],
    ['Пример:', [
        { p = 'Voy a comprar frutas.' },
        { p = 'Я куплю фрукты (я собираюсь купить фрукты).' }
    ]],
    ['Использование 2:', [
        { p = 'Удивление, недоверие, неодобрение или замешательство о настоящем времени или о будущем.' }
    ]],
    ['Примеры', [
        { p = '¿Cómo vas a hacer algo tan insensato?' },
        { p = 'Как ты можешь совершить такой безрассудный поступок!?' }
        { p = '¡Qué va a ser millonario! ¡Es mitómano!' },
        { p = 'Какой из него миллионер!? Он - лжец!' }
    ]]
]

['Futuro indicativo']
title = ['1: Будущее время', '2: Гипотеза о настоящем времени']
description = [
    ['Использование 1:', [
        { p = 'Обещания и предсказания.' }, 
        { p = 'Будущее время.' }
    ]],
    ['Пример:', [
        { p = 'Volveremos la semana que viene.' },
        { p = 'Мы вернёмся на следующей неделе.' }
    ]],
    ['Использование 2:', [
        { p = 'Задаваться вопросом, интересоваться или гипотеза о настоящем времени.' }
    ]],
    ['Примеры', [
        { p = '¿No sabrá qué hacer?' },
        { p = 'Разве он может не знать, что делать!?' }
        { p = '¿Estará vivo Elvis?' },
        { p = 'Разве Элвис жив!?' }
    ]]
]

['Preterito perfecto compuestos del subjuntivo']
title = ['1: Процесс будет завершён как условие для другого действия', '2: Сослагательное наклонение 1 ограничено прошлым']
description = [
    ['Использование 1:', [
        { p = 'Обещания и предсказания.' },
        { p = 'Условие будет завершено, за которым последует другое действие ("после того, как").' }
    ]],
    ['В сочетании с:', [
        { p = 'Предложениями в будущем.' }
    ]],
    ['Пример:', [
        { p = 'Cuando <u>hayas terminado</u> de leer el manual, podrás resolver el problema.' },
        { p = 'После того, как закончишь читать инструкцию, ты сможешь решить проблему.' }
    ]],
    ['Использование 2:', [
        { p = 'Придаточное предложение после "чтобы" или "что" ограничено прошлым.' }
    ]],
    ['В сочетании с:'], [
        { p = 'Предложениями в настоящем времени или в прошедшем времени совершенного вида.' }
    ]],
    ['Примеры', [
        { p = 'Los documentos no demuestran que <u>haya vivido</u> en otro país.' },
        { p = 'Документы не доказывают, что он проживал в другой стране.' },
        { p = 'No creo que él <u>se haya dado</u> cuenta.' },
        { p = 'Я не думаю, что он заметил.' }
    ]]
]

['Futuro perfecto compuestas comunes']
title = ['1: Действие будет завершено до другого момента в будущем', '2: Гипотеза о прошлом']
description = [
    ['Использование 1:', [
        { p = 'Обещания и предсказания.' },
        { p = 'Действие будет завершено до другого момента в будущем.' }
    ]],
    ['В сочетании с:', [
        { p = '"Сослагательное наклонение 1".' }
    ]],
    ['Пример:', [
        { p = 'Cuando lleguemos <u>habrán cerrado</u> las puertas.' },
        { p = 'Когда мы доберёмся, двери будут закрыты (сейчас они ещё открыты).' }
    ]],
    ['Использование 2:', [
        { p = 'Гипотеза или задаваться вопросом, интересоваться о прошлом.' },
        { p = '"Haber" указывает, что гипотеза касается прошлого.' }
    ]],
    ['Пример', [
        { p = 'Habrá anotado mal el número.' },
        { p = 'Должно быть, он неправильно записал номер.' }
    ]]
]

['Futuro perfecto con Ir a']
title = ['1: Действие будет завершено до другого момента в будущем', '2: Недоверие о прошлом']
description = [
    ['Использование 1:', [
        { p = 'Обещания и предсказания.' },
        { p = 'Действие будет завершено до другого момента в будущем.' }
    ]],
    ['В сочетании с:', [
        { p = '"Сослагательное наклонение 1".' }
    ]],
    ['Пример:', [
        { p = 'Cuando vengas <u>voy a haber preparado</u> todo.' },
        { p = 'Когда ты придёшь (сюда), я (уже) всё подготовлю.' }
    ]],
    ['Использование 2:', [
        { p = 'Удивление, недоверие, неодобрение или замешательство о прошлом.' }
    ]],
    ['Пример', [
        { p = '¿Qué se va a haber recibido en MGU?' },
        { p = 'Да какой МГУ он закончил?!' }
    ]]
]

['Presente subjuntivo']
title = ['Сослагательное наклонение 1']
description = [
    ['Использование 1:', [
        { p = 'Пожелания или требования.' },
        { p = 'Придаточное предложение после "чтобы" или "что".' }
    ]],
    ['В сочетании с:', [
        { p = 'Предложениями в настоящем или будущем времени.' }
    ]],
    ['Примеры:', [
        { p = 'Ella quiere que la <u>ayudemos</u>.' },
        { p = 'Она хочет, чтобы мы ей помогли.' },
        { p = 'No creo que él <u>se dé</u> cuenta.' },
        { p = 'Я не думаю, что он заметит.' }
    ]],
    ['Использование 2:', [
        { p = 'Обещания и предсказания.' },
        { p = 'Условие в будущем. "Когда".' }
    ]],
    ['В сочетании с:', [
        { p = 'Предложениями в будущем времени или в повелительном наклонении.' }
    ]],
    ['Пример', [
        { p = 'Te escribiré cuando <u>llegue</u> a la oficina.' },
        { p = 'Я напишу тебе, когда приеду в офис.' }
    ]],
    ['Использование 3:', [
        { p = '"Возможно" (о настоящем времени или о будущем).' }
    ]],
    ['Пример', [
        { p = 'Quizás lo <u>intentemos</u> de nuevo.' },
        { p = 'Возможно, мы попытаемся снова.' }
    ]]
]

['Imperfecto subjuntivo']
title = ['Сослагательное наклонение 2']
description = [
    ['Использование 1:', [
        { p = 'Пожелания или требования.' },
        { p = 'Придаточное предложение после "чтобы" или "что".' }
    ]],
    ['В сочетании с:', [
        { p = 'Предложениями в прошедшем времени.' }
    ]],
    ['Схема:', [
        { p = 'Корень + "ase"/"ara" | "iese"/"iera".' }
    ]],
    ['Пример:', [
        { p = 'Ella nos pidió que la <u>ayudásemos</u>.' },
        { p = 'Она попросила нас, чтобы мы ей помогли.' }
    ]],
    ['Использование 2:', [
        { p = 'Невероятное или невозможное условие, в настоящем времени и в будущем ("если бы").' }
    ]],
    ['В сочетании с:', [
        { p = '"Следствие маловероятных условии "бы"".' }
    ]],
    ['Пример:', [
        { p = 'Si <u>tuviese</u> una lancha iría a la isla.' },
        { p = 'Если бы у меня была лодка, я бы отправился на остров.' }
    ]]
]

['Futuro subjuntivo']
title = ['Сослагательное наклонение 3']
description = [
    ['Использование:', [
        { p = 'Вероятное и возможное условие, в будущем ("если" или "когда").' },
        { p = 'Очень официально. Обычно, в юридических текстах.' }
    ]],
    ['В сочетании с:', [
        { p = 'Предложениями в будущем.' }
    ]],
    ['Схема:', [
        { p = 'Корень + "are"/"iere".' }
    ]],
    ['Пример:', [
        { p = 'Si el proveedor no <u>entregare</u> el producto dentro de los tres días habiles, la empresa podrá rescindir el contrato.' },
        { p = 'Если поставщик не доставит товар в течение трёх рабочих дней, компания сможет расторгнуть договор.' }
    ]]
]

['Pluscuamperfecto compuestos del subjuntivo']
title = ['Сослагательное наклонение 2 в прошлом (так и не произошло)']
description = [
    ['Использование:', [
        { p = 'Условие, которое не исполнилось в прошлом и уже невозможно ("если бы").' },
        { p = '"Haber" отодвигает условие в прошлое.' }
    ]],
    ['В сочетании с:', [
        { p = '"Следствие невыполненного условия в прошлом "бы""' }
    ]],
    ['Примеры:', [
        { p = 'Si ella me <u>hubiese dicho</u> que iba a venir con amigos, habría preparado más comida.' },
        { p = 'Если бы она сказала мне, что она собиралась прийти с друзьями, я бы приготовил больше еды.' },
        { p = 'Si mi abuela no <u>se hubiese muerto</u>, estaría viva. (Выражение)' },
        { p = 'Если бы моя бабушка не умерла, она была бы жива.' }
    ]]
]

['Condicional indicativo']
title = ['1: Следствие маловероятных условий "бы"', '2: Предсказание в прошлом']
description = [
    ['Использование 1:', [
        { p = 'Последствие если условие выполняется. Совет.' }
    ]],
    ['В сочетании с:', [
        { p = '"Сослагательное наклонение 2"' }
    ]],
    ['Схема:', [
        { p = 'Инфинитив + "ía".' }
    ]],
    ['Примеры:', [
        { p = 'Si tuviese mis herramientas aquí lo <u>repararía</u>.' },
        { p = 'Если бы у меня были здесь инструменты, я бы починил.' },
        { p = 'Yo no iría a ese lugar.' },
        { p = 'Я бы туда не ходил.' }
    ]],
    ['Использование 2:', [
        { p = 'Предположение о будущем в прошлом.' }
    ]],
    ['В сочетании с:', [
        { p = 'Предложениями в прошедшем времени.' }
    ]],
    ['Пример:', [
        { p = 'Creí que <u>sería</u> más difícil.' },
        { p = 'Я думал, что <u>будет</u> сложнее.' }
    ]],
]

['Condicional perfecto compuestas comunes']
title = ['Следствие невыполненного условия в прошлом "бы"']
description = [
    ['Использование:', [
        { p = 'Последствие, которое не было выполнено в прошлом и уже невозможно.' },
        { p = '"Haber" отодвигает последствие в прошлое.' }
    ]],
    ['В сочетании с:', [
        { p = '"Сослагательное наклонение 2 в прошлом (так и не произошло)"' }
    ]],
    ['Пример:', [
        { p = 'Si hubiésemos sabido cómo se comporta la gente aquí en año nuevo, <u>habríamos viajado</u> en otro momento.' },
        { p = 'Если бы мы знали, как люди ведут себя здесь в Новый год, мы бы приехали в другой момент.' }
    ]]
]

['Podria haber']
title = ['Возможность ограничена прошлым']
description = [
    ['Использование:', [
        { p = 'Действие, которое не произошло, но было возможно в прошлом.' },
        { p = '"Haber" отодвигает возможность в прошлое.' }
    ]],
    ['Пример:', [
        { p = '¡Podrías haber incendiado la casa con tus experimentos!' },
        { p = 'Ты (же) мог поджечь дом своими экспериментами!' }
    ]]
]

['Deberia haber']
title = ['Желательное поведение ограничено прошлым "следовало бы"']
description = [
    ['Использование:', [
        { p = 'Желаемое действие, которое не произошло и уже поздно.' }
    ]],
    ['Пример:', [
        { p = '<u>Deberíamos haber comprado</u> oro hace dos años.' },
        { p = 'Нам следовало бы купить золото два года назад.' }
    ]]
]

['Puede haber']
title = ['1: Гипотеза о прошлом', '2: (Отрицательное) утверждение о невозможности в прошлом']
description = [
    ['Использование 1:', [
        { p = 'Гипотеза о прошлом (низкий уровень уверенности).' },
        { p = 'С "haber" гипотеза ограничена прошлым событием.' }
    ]],
    ['Пример:', [
        { p = '<u>Pueden haber cambiado</u> la clave y no nos han dicho nada.' },
        { p = 'Может быть они сменили пароль и (пока) не сообщили нам об этом.' }
    ]],
    ['Использование 2:', [
        { p = 'Утверждение о невозможности в прошлом (только в отрицательных предложениях)' }
    ]],
    ['Пример:', [
        { p = 'Yo <u>no puedo haber asesinado</u> al mayordomo pues a esa hora me encontraba en el teatro.' },
        { p = 'Я не мог убить дворецкого, так как в это время я был в театре.' }
    ]]
]

['Debe haber']
title = ['Вывод о прошлом']
description = [
    ['Использование:', [
        { p = 'Вывод о прошлом (высокий уровень уверенности).' },
        { p = '"Haber" отодвигает вывод на действие прошлого.' }
    ]],
    ['Пример:', [
        { p = 'Debe haberse quedado dormido.' },
        { p = 'Должно быть, он проспал.' }
    ]]
]