['main']
node = [ 'ИСПОЛЬЗОВАНИЕ НАИБОЛЕЕ РАСПРОСТРАНЕННЫХ ВСПОМОГАТЕЛЬНЫХ ГЛАГОЛОВ' ]
values = [ 'Связка', 'Наличие', 'Значение' ]

['Haber + participio']
node = [ 'Haber + participio' ]
values = [
    { g = '✓' },
    { e = 'Указывает на действие, которое произошло до момента, о котором идёт речь.'},
    { r = '✗' },
    { e = 'Действие относится только к определённому моменту времени.'}
]

['Estar + gerundio']
node = [ 'Estar + gerundio' ]
values = [
    { g = '✓' },
    { e = 'Определяет процесс, который происходит краткосрочно и постоянно.'},
    { r = '✗' },
    { e = 'Описывает мгновенное или долгосрочное действие.'}
]

['Ser + participio']
node = [ 'Ser + participio' ]
values = [
    { g = '✓' },
    { e = 'Используется для выражения страдательного залога.'},
    { r = '✗' },
    { e = 'Означает действительный залог.'}
]

['Ir a + infinitivo']
node = [ 'Ir a + infinitivo' ]
values = [
    { g = '✓' },
    { e = 'Означает намерение, предсказание или будущее действие.'}
]

['Poder + infinitivo']
node = [ 'Poder + infinitivo' ]
values = [
    { g = '✓' },
    { e = 'Указывает на возможность выполнения действия.'}
]

['Deber + infinitivo']
node = [ 'Deber + infinitivo' ]
values = [
    { g = '✓' },
    { e = 'Выражает обязанность, желательное действие или необходимость.'}
]
