table_header = ['ИСПОЛЬЗОВАНИЕ НАИБОЛЕЕ РАСПРОСТРАНЕННЫХ ВСПОМОГАТЕЛЬНЫХ ГЛАГОЛОВ']
table_columns = ['Вспомогательная связка', 'Наличие во фразе', 'Значение']

['Haber + participio']
values = [
    { '✓': 'Указывает на действие, которое произошло до момента, о котором идёт речь.' },
    { '✗': 'Действие относится только к определённому моменту времени.' }
]

['Estar + gerundio']
values = [
    { '✓': 'Определяет процесс, который происходит краткосрочно и постоянно.'},
    { '✗': 'Описывает мгновенное или долгосрочное действие.' }
]

['Ser + participio']
values = [
    { '✓': 'Используется для выражения страдательного залога.' },
    { '✗': 'Означает действительный залог.' }
]

['Ir a + infinitivo']
values = [
    { '✓': 'Означает намерение, предсказание или будущее действие.' }
]

['Poder + infinitivo']
values = [
    { '✓': 'Указывает на возможность выполнения действия.' }
]

['Deber + infinitivo']
values = [
    { '✓': 'Выражает обязанность, желательное действие или необходимость.' }
]
